### PR TITLE
@dzucconi - removes brunch, adds gulp

### PR DESCRIPTION
**Pull request by broskoski**
This restructures this project to work with your gulp boilerplate. All the routes are kept in tact (they all still work!), probably a good idea to just have a swiss army knife of possibilities in terms of what to offer a potential fair.

Currently the build process converts env vars to strings via envify. This seems somehow less than ideal, but in reality probably isn't a huge deal as the monoliths won't be web accessible. Will also adapt your older specs to this project in a future PR.

### CODE REVIEW

**Comment by dzucconi** [comment]
I'm going to hold off on merging this until we talk and I take a closer look... but some things: we definitely do want it to be web accessible so that we are able to push updates to them while deployed without having to physically access the computers, among other reasons. Also I figure we'll still want a server under this so that we could safely authenticate with the API; etc.

**Comment by broskoski** [comment]
Sounds good. FYI was still planning on using pusher (or socket.io alternatively) to connect to Europa (which would handle all the pushing updates, restarting, etc).

**Comment by broskoski** [comment]
Re: our slack convo - the modified plan is to throw a small express server in front to serve monolith html (which loads the backbone app) on Heroku.

**Comment by broskoski** [comment]
Already abandoned this approach, closing

**Pull request closed without merging**
